- name: fail when hostname is not specified
  fail:
    msg: "hostname not specified"
  when:
    - hostname is not defined
- name: fail when heap size is not specified
  fail:
    msg: "heap_size not specified"
  when:
    - heap_size is not defined
- name: "修改主机名"
  hostname:
    name: "{{ hostname|quote }}"
  tags: hostname
- name: "关闭selinux"
  selinux:
    state: disabled
  tags: selinux
- name: "关闭防火墙"
  systemd:
    name: firewalld
    enabled: no
    state: stopped
  tags: iptables
- name: "添加ELK软件源"
  yum_repository:
    file: epel
    name: epel
    description: ELK repository for 7.x packages
    baseurl: "https://mirrors.tuna.tsinghua.edu.cn/elasticstack/7.x/yum/"
    gpgcheck: no
    enabled: yes
  tags: repo
- name: "添加logstash组"
  group:
    name: "{{ logstash_group }}"
    gid: "{{ logstash_group_id }}"
    system: yes
    state: present
  tags: group
- name: "添加logstash用户"
  user:
    name: "{{ logstash_user }}"
    uid: "{{ logstash_user_id }}"
    group: "{{ logstash_group }}"
    createhome: no
    comment: logstash system user
    system: yes
    state: present
  tags: user
- name: "修改内核参数"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    ignoreerrors: yes
    reload: yes
  with_items:
    - {name: 'vm.max_map_count',value: '262144' }
  tags: sysctl
- name: "创建logstash目录"
  file:
    path: "{{ item }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: "2750"
    state: directory
  with_items:
    - "{{ logstash_log_dir }}"
    - "{{ logstash_data_dir }}"
  tags: dir
- name: "安装JDK"
  yum:
    name: "java-1.8.0-openjdk"
    update_cache: yes
    state: present
- name: "安装logstash"
  yum:
    name: '{{ logstash_package_name }}{% if logstash_version is defined and logstash_version != ""  %}-{{ logstash_version }}{% endif %}'
    update_cache: yes
    state: present
- name: "修改jvm.options"
  template:
    src: "jvm.options.j2"
    dest: "/etc/logstash/jvm.options"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: "0660"
    force: yes
    backup: yes
  notify: restart logstash
  tags: jvm
- name: "修改配置文件"
  template:
    src: "logstash.yml.j2"
    dest: "/etc/logstash/logstash.yml"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: "0660"
    force: yes
    backup: yes
  notify: restart logstash
  tags: conf
- name: "修改配置文件"
  template:
    src: "logs.conf.j2"
    dest: "/etc/logstash/conf.d/logs.conf"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: "0660"
    force: yes
    backup: yes
  notify: restart logstash
  tags: logs
