- name: fail when hostname is not specified
  fail:
    msg: "hostname not specified"
  when:
    - hostname is not defined
- name: "修改主机名"
  hostname:
    name: "{{ hostname|quote }}"
  tags: hostname
- name: "关闭selinux"
  selinux:
    state: disabled
  tags: selinux
- name: "关闭防火墙"
  systemd:
    name: firewalld
    enabled: no
    state: stopped
  tags: iptables
- name: "添加ELK软件源"
  yum_repository:
    file: epel
    name: epel
    description: ELK repository for 7.x packages
    baseurl: "https://mirrors.tuna.tsinghua.edu.cn/elasticstack/7.x/yum/"
    gpgcheck: no
    enabled: yes
  tags: repo
- name: "修改内核参数"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    ignoreerrors: yes
    reload: yes
  with_items:
    - {name: 'vm.max_map_count',value: '262144' }
  tags: sysctl
- name: "安装kibana"
  yum:
    name: '{{ kibana_package_name }}{% if kibana_version is defined and kibana_version != ""  %}-{{ kibana_version }}{% endif %}'
    update_cache: yes
    state: present
- name: "修改配置文件"
  template:
    src: "kibana.yml.j2"
    dest: "/etc/kibana/kibana.yml"
    owner: "kibana"
    group: "kibana"
    mode: "0660"
    force: yes
    backup: yes
  notify: restart kibana
  tags: conf
